const today = new Date().toISOString().split('T')[0];

export const initialData = {
    clubName: '',
    clubLogoUrl: '',
    president: '',
    vicePresident: '',
    secretary: '',
    numeroAffiliation: '',
    region: '',
    zone: '',
    reunionType: '',
    meetingDate: today,
    location: '',
    startTime: '',
    endTime: '',
    memberPresent: '0',
    memberExcused: '0',
    memberAbsent: '0',
    guests: '0',
    memberTotal: '0',
    presidentWord: '',
    orderOfDay: '',
    approvalPV: '',
    receivedMails: '',
    sentMails: '',
    adminBalance: '',
    worksBalance: '',
    headQuartersFees: '',
    districtFees: '',
    regionFees: '',
    treasuryOther: '',
    pointEME: '',
    pointEML: '',
    pointEMS: '',
    ongoingActions: '',
    pointLCIF: '',
    marketing: '',
    monthProgram: '',
    miscellaneous: '',
};